//
//  Swift2KotlinGenerator.swift
//  swift-java
//
//  Created by Tanish Azad on 02/04/26.
//

import CodePrinting
import SwiftJavaConfigurationShared
import SwiftExtract

package class Swift2KotlinGenerator: Swift2JavaGenerator {
  let log: Logger
  let config: Configuration
  let analysis: AnalysisResult
  let swiftModuleName: String
  let kotlinPackage: String
  let swiftOutputDirectory: String
  let kotlinOutputDirectory: String
  let lookupContext: SwiftTypeLookupContext

  var kotlinPackagePath: String {
    kotlinPackage.replacingOccurrences(of: ".", with: "/")
  }

  package init(
    config: Configuration,
    translator: SwiftAnalyzer,
    kotlinPackage: String,
    swiftOutputDirectory: String,
    kotlinOutputDirectory: String,
  ) {
    self.log = Logger(label: "kotlin-generator", logLevel: translator.log.logLevel)
    self.config = config
    self.analysis = translator.result
    self.swiftModuleName = translator.swiftModuleName
    self.kotlinPackage = kotlinPackage
    self.swiftOutputDirectory = swiftOutputDirectory
    self.kotlinOutputDirectory = kotlinOutputDirectory
    self.lookupContext = translator.lookupContext
 }

  func generate() throws {
    try writeExportedJavaSources()
    log.info("Generated Kotlin sources (package: '\(kotlinPackage)') in: \(kotlinOutputDirectory)/")
  }
}

extension Swift2KotlinGenerator {
  package func writeExportedJavaSources() throws {
    var printer = KotlinPrinter()
    try writeExportedKotlinSources(printer: &printer)
  }

  /// Every imported public type becomes a public class in its own file in Java.
  package func writeExportedKotlinSources(printer: inout KotlinPrinter) throws {
    for (_, ty) in analysis.extractedTypes.sorted(by: { (lhs, rhs) in lhs.key < rhs.key }) {
      let filename = "\(ty.swiftNominal.name).kt"
      log.debug("Printing contents: \(filename)")
      printExtractedNominal(&printer, ty)

      if let outputFile = try printer.writeContents(
        outputDirectory: kotlinOutputDirectory,
        javaPackagePath: kotlinPackagePath,
        filename: filename
      ) {
        log.info("Generated: \((ty.swiftNominal.name.bold + ".kt").bold) (at \(outputFile.absoluteString))")
      }
    }

    do {
      let filename = "\(self.swiftModuleName).kt"
      log.debug("Printing contents: \(filename)")
      printModule(&printer)

      if let outputFile = try printer.writeContents(
        outputDirectory: kotlinOutputDirectory,
        javaPackagePath: kotlinPackagePath,
        filename: filename
      ) {
        log.info("Generated: \((self.swiftModuleName + ".kt").bold) (at \(outputFile.absoluteString))")
      }
    }
  }
}

// ==== ---------------------------------------------------------------------------------------------------------------
// MARK: Kotlin/text printing

extension Swift2KotlinGenerator {
  /// Render the Java file contents for an imported Swift module.
  ///
  /// This includes any Swift global functions in that module, and some general type information and helpers.
  func printModule(_ printer: inout KotlinPrinter) {
    printHeader(&printer)
    printPackage(&printer)
    
    for decl in analysis.extractedGlobalVariables {
      self.log.trace("Print imported decl: \(decl)")
      printKotlinBindingPlaceholder(&printer, decl)
    }
    
    for decl in analysis.extractedGlobalVariables {
      self.log.trace("Print imported decl: \(decl)")
      printKotlinBindingPlaceholder(&printer, decl)
    }
  }
  
  func printExtractedNominal(_ printer: inout KotlinPrinter, _ decl: ExtractedNominalType) {
    printHeader(&printer)
    printPackage(&printer)
    
    printNominal(&printer, decl) { printer in
      var decls = decl.initializers
      decls.append(contentsOf: decl.methods)
      decls.append(contentsOf: decl.variables)
      let partitionedDecls = decls.partition {
        switch $0.functionSignature.selfParameter {
        case .staticMethod, .initializer, nil:
          return true
        default:
          return false
        }
      }
      
      printCompanionObject(&printer) { printer in
        for staticDecl in decls[partitionedDecls...] {
          printKotlinBindingPlaceholder(&printer, staticDecl)
        }
      }
      
      for decl in decls[..<partitionedDecls] {
        printKotlinBindingPlaceholder(&printer, decl)
      }
      
      // Helper methods and default implementations
      printToStringMethod(&printer, decl)
    }
  }
  
  func printHeader(_ printer: inout KotlinPrinter) {
    printer.print(
      """
      // Generated by jextract-swift
      // Swift module: \(swiftModuleName)
      
      """
    )
  }
  
  func printPackage(_ printer: inout KotlinPrinter) {
    printer.print(
      """
      package \(kotlinPackage)
      
      """
    )
  }
  
  func printNominal(
    _ printer: inout KotlinPrinter,
    _ decl: ExtractedNominalType,
    body: (inout KotlinPrinter) -> Void
  ) {
    printer.printBraceBlock(
      "class \(decl.swiftNominal.name) private constructor()"
    ) { printer in
      body(&printer)
    }
  }
  
  func printCompanionObject(_ printer: inout KotlinPrinter, body: (inout KotlinPrinter) -> Void) {
    printer.printBraceBlock("companion object") { printer in
      body(&printer)
    }
  }

  func printToStringMethod(
    _ printer: inout KotlinPrinter,
    _ decl: ExtractedNominalType
  ) {
    printer.print(
      """
      override fun toString(): String {
          TODO("Not implemented")
      }
      """
    )
  }

}
